# Generated by Django 2.2.4 on 2021-04-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedList',
        ),
    ]
