version: '3.8'

services:
  moviematch:
    image: django:debug
    env_file:
      - ./.env
    environment:
    - DJANGO_SETTINGS_MODULE=movie_match.settings.docker_dev
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - type: bind
        source: "/d/User Data/Documents/Code Projects/Portfolio/Docker/moviematch_staticfiles"
        target: /app/staticfiles