version: '3.8'

services:
  moviematch:
    image: django:development
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: "/d/User Data/Documents/Code Projects/Portfolio/Docker/moviematch_staticfiles"
        target: /app/staticfiles
  redis:
    image: redis:5-alpine
    ports:
        - 6379:6379
