version: '3.8'

services:
  moviematch:
    image: django:production
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  redis:
    image: redis:5-alpine
    ports:
        - 6379:6379
