version: '3.8'

name: moviematch-app
services:
  
  django_app:
    image: ${IMAGE_NAME}
    env_file:
      - ./app.env
    environment:
      - DJANGO_SETTINGS_MODULE=movie_match.settings.prod
      - CONTAINER_STATIC_DIRECTORY
    ports:
      - 8000:8000
      - 8001:8001
    command: ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 movie_match.wsgi & daphne -b 0.0.0.0 -p 8001 movie_match.asgi:application"]
    restart: always
    volumes:
      - type: bind
        source: "${LOCAL_STATIC_DIRECTORY}"
        target: /app/${CONTAINER_STATIC_DIRECTORY}
  
  redis:
    image: redis:7-alpine
    ports:
        - 6379:6379
    restart: always
  
  postgres_db:
    env_file:
      - ./app.env
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  default:
    name: moviematch_network
