name: moviematch-dev
services:
  django-app:
    image: django:development
    environment:
      - DJANGO_SETTINGS_MODULE=movie_match.settings.docker_dev
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]

