version: '3.8'

services:
  moviematch:
    image: django:production
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=movie_match.settings.docker_prod
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: "/d/User Data/Documents/Code Projects/Portfolio/Docker/moviematch_staticfiles"
        target: /app/staticfiles
  redis:
    image: redis:5-alpine
    ports:
        - 6379:6379
