# Generated by Django 2.2.4 on 2022-02-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmovielist',
            name='sharecode',
            field=models.CharField(default='YUmGptqEx', max_length=255, unique=True),
        ),
    ]
