# Generated by Django 2.2.4 on 2022-02-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_and_reg', '0001_initial'),
        ('display_app', '0002_auto_20220220_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmovielist',
            name='sharecode',
            field=models.CharField(default='2NzKxPQiq', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('is_Registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UUID', to='app_login_and_reg.User')),
            ],
        ),
    ]
