# Generated by Django 2.2.4 on 2021-04-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0002_delete_sharedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(related_name='in_shared_lists', to='display_app.Movie')),
            ],
        ),
    ]
