# Generated by Django 2.2.4 on 2021-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0003_sharedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlist',
            name='chosen',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
