# Generated by Django 2.2.4 on 2022-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0003_added_uuid_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmovielist',
            name='sharecode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
