# Generated by Django 2.2.4 on 2022-02-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_and_reg', '0001_initial'),
        ('display_app', '0004_sharedlist_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_lists', to='app_login_and_reg.User')),
                ('movies', models.ManyToManyField(related_name='in_saved_lists', to='display_app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='SharedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.TextField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_movies', to='display_app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='SharedMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(related_name='in_temp_lists', to='display_app.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='sharedlist',
            name='movies',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='SharedList',
        ),
        migrations.AddField(
            model_name='sharedmovie',
            name='shared_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_movies', to='display_app.SharedMovieList'),
        ),
    ]
