# Generated by Django 2.2.4 on 2022-02-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0004_overrode_shared_save_to_retry_when_not_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedmovie',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='sharedmovie',
            name='submitted_by',
            field=models.ManyToManyField(related_name='submitted_movies', to='display_app.UserUUID'),
        ),
        migrations.RemoveField(
            model_name='sharedmovielist',
            name='users',
        ),
        migrations.AddField(
            model_name='sharedmovielist',
            name='users',
            field=models.ManyToManyField(related_name='shared_lists', to='display_app.UserUUID'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_lists', to='display_app.UserUUID'),
        ),
    ]
