# Generated by Django 2.2.4 on 2022-02-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0005_temp_shared_lists_and_movies_linked_to_UUIDmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_path',
        ),
    ]
