# Generated by Django 2.2.4 on 2022-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0005_auto_20220219_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmovielist',
            name='sharecode',
            field=models.CharField(default='3HU23v7q', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedmovie',
            name='submitted_by',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='sharedmovielist',
            name='users',
            field=models.TextField(default='[]'),
        ),
    ]
