# Generated by Django 2.2.4 on 2022-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0006_rename_poster_to_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmovie',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
