# Generated by Django 2.2.4 on 2022-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0007_add_eliminated_field_to_shared_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruuid',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
