# Generated by Django 2.2.4 on 2022-03-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0008_add_nickname_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined', models.ManyToManyField(null=True, related_name='joined_room', to='display_app.UserUUID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_room', to='display_app.SharedMovieList')),
            ],
        ),
    ]
