# Generated by Django 2.2.4 on 2022-03-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0009_added_model_for_match_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchroom',
            old_name='room',
            new_name='list',
        ),
    ]
