# Generated by Django 2.2.4 on 2022-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0010_changed_attr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchroom',
            name='joined',
            field=models.ManyToManyField(related_name='joined_room', to='display_app.UserUUID'),
        ),
    ]
