# Generated by Django 2.2.4 on 2022-03-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0011_removed_superfluous_null_prop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sharedmovielist',
            old_name='users',
            new_name='contributors',
        ),
        migrations.DeleteModel(
            name='MatchRoom',
        ),
        migrations.AddField(
            model_name='shareroomuser',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='display_app.SharedMovieList'),
        ),
        migrations.AddField(
            model_name='shareroomuser',
            name='user_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_room', to='display_app.UserUUID'),
        ),
        migrations.AddConstraint(
            model_name='shareroomuser',
            constraint=models.UniqueConstraint(fields=('user_uuid', 'list'), name='one_user_per_room'),
        ),
    ]
