# Generated by Django 2.2.4 on 2022-03-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0012_removed_match_room_added_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareroomuser',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
