# Generated by Django 2.2.4 on 2022-03-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0013_nickname_for_shareroomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_lists', to='display_app.UserUUID'),
        ),
        migrations.AddField(
            model_name='sharedmovielist',
            name='started_eliminating',
            field=models.BooleanField(default=False),
        ),
    ]
