# Generated by Django 2.2.4 on 2022-03-19 08:30

from django.db import migrations

def update_created_by(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SharedMovieList = apps.get_model('display_app', 'SharedMovieList')
    for shared_list in SharedMovieList.objects.all():
        contributor = shared_list.contributors.first()
        shared_list.created_by = contributor
        shared_list.save()

class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0014_createdBy_and_startedEliminating_fields_for_SharedList'),
    ]

    operations = [
        migrations.RunPython(update_created_by)
    ]
