# Generated by Django 2.2.4 on 2022-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0014_createdBy_and_startedEliminating_fields_for_SharedList'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareroomuser',
            name='is_users_turn',
            field=models.BooleanField(default=False),
        ),
    ]
