# Generated by Django 2.2.4 on 2022-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0015_is_users_turn_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareroomuser',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='shareroomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
