# Generated by Django 2.2.4 on 2022-03-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0016_is_active_attr_on_shareuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareroomuser',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_users', to='display_app.SharedMovieList'),
        ),
    ]
