# Generated by Django 2.2.4 on 2022-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_app', '0017_rename_active_users_to_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareroomuser',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
