# Generated by Django 2.2.4 on 2022-04-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharecode', models.CharField(max_length=255, unique=True)),
                ('started_eliminating', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributors', models.ManyToManyField(related_name='shared_lists', to='list_builder.UserUUID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_lists', to='list_builder.UserUUID')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_users_turn', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('last_active', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_users', to='elimination_room.SharedMovieList')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_room', to='list_builder.UserUUID')),
            ],
        ),
        migrations.CreateModel(
            name='SharedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eliminated', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_movies', to='list_builder.Movie')),
                ('shared_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_movies', to='elimination_room.SharedMovieList')),
                ('submitted_by', models.ManyToManyField(related_name='submitted_movies', to='list_builder.UserUUID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shareroomuser',
            constraint=models.UniqueConstraint(fields=('user_uuid', 'list'), name='one_user_per_room'),
        ),
    ]
