# Generated by Django 2.2.4 on 2022-05-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shareroomuser',
            name='one_user_per_room',
        ),
        migrations.RenameField(
            model_name='shareroomuser',
            old_name='user_uuid',
            new_name='persona',
        ),
        migrations.AddConstraint(
            model_name='shareroomuser',
            constraint=models.UniqueConstraint(fields=('persona', 'list'), name='one_user_per_room'),
        ),
    ]
