# Generated by Django 4.0.5 on 2022-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0002_change_fields_to_reflect_persona_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmovie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharedmovielist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shareroomuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
