# Generated by Django 4.1 on 2023-08-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0003_change_primarykeys_to_bigautofield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedmovielist',
            old_name='started_eliminating',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='shareroomuser',
            name='is_users_turn',
        ),
        migrations.RemoveField(
            model_name='shareroomuser',
            name='last_active',
        ),
        migrations.AddField(
            model_name='sharedmovielist',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shareroomuser',
            name='has_eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareroomuser',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
