# Generated by Django 4.1 on 2023-09-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0004_updated_list_voting_round_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareroomuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shareroomuser',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
