# Generated by Django 4.1 on 2023-11-03 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0005_nickname_no_longer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareroomuser',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Optional. 20 characters or fewer. Letters, numbers, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', max_length=20, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', regex='^[\\w,.!:\\"\' $&+\\-()]+\\Z')]),
        ),
    ]
