# Generated by Django 4.1 on 2023-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0006_roomuser_nickname_regex_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmovielist',
            name='sharecode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
