# Generated by Django 4.1 on 2023-11-06 00:21

from django.db import migrations, models
import list_builder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0007_sharecode_max_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareroomuser',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Optional. 20 characters or fewer. Letters, numbers, basic punctuation: , . ! ? : \' " $ & + - ( ) characters.', max_length=20, validators=[list_builder.validators.UserInputValidator()]),
        ),
    ]
