# Generated by Django 4.2.7 on 2023-11-23 12:42

from django.db import migrations, models
import django.db.models.deletion
import list_builder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0016_remove_unused_field'),
        ('elimination_room', '0008_custom_validator_class'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shareroomuser',
            name='one_user_per_room',
        ),
        migrations.CreateModel(
            name='EliminationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharecode', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('turn', models.IntegerField(default=0)),
                ('contributors', models.ManyToManyField(related_name='elimination_sessions', to='list_builder.persona')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_elimination_sessions', to='list_builder.persona')),
            ],
        ),
        migrations.CreateModel(
            name='EliminationSessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, default='', help_text='Optional. 20 characters or fewer. Letters, numbers, basic punctuation: , . ! ? : \' " $ & + - ( ) characters.', max_length=20, validators=[list_builder.validators.UserInputValidator()])),
                ('has_eliminated', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elimination_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_users', to='elimination_room.eliminationsession')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_session', to='list_builder.persona')),
            ],
        ),
        migrations.RemoveField(
            model_name='shareroomuser',
            name='list',
        ),
        migrations.RemoveField(
            model_name='shareroomuser',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='sharedmovie',
            name='shared_list',
        ),
        migrations.DeleteModel(
            name='SharedMovieList',
        ),
        migrations.DeleteModel(
            name='ShareRoomUser',
        ),
        migrations.AddField(
            model_name='sharedmovie',
            name='elimination_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_movies', to='elimination_room.eliminationsession'),
        ),
        migrations.AddConstraint(
            model_name='eliminationsessionuser',
            constraint=models.UniqueConstraint(fields=('persona', 'elimination_session'), name='one_user_per_session'),
        ),
    ]
