# Generated by Django 2.2.4 on 2022-04-24 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruuid',
            old_name='is_Registered',
            new_name='is_registered',
        ),
    ]
