# Generated by Django 2.2.4 on 2022-04-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_builder', '0002_change_capitalization_of_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_lists', to='list_builder.UserUUID'),
        ),
        migrations.AddField(
            model_name='useruuid',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uuid', to=settings.AUTH_USER_MODEL),
        ),
    ]
