# Generated by Django 2.2.4 on 2022-05-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0003_related_auth_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedmovielists', to='list_builder.UserUUID'),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='movies',
            field=models.ManyToManyField(related_name='in_savedmovielists', to='list_builder.Movie'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempmovielists', to='list_builder.UserUUID'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='movies',
            field=models.ManyToManyField(related_name='in_tempmovielists', to='list_builder.Movie'),
        ),
    ]
