# Generated by Django 2.2.4 on 2022-05-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0004_abstracted_movie_list_base_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
