# Generated by Django 2.2.4 on 2022-05-17 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elimination_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_builder', '0005_desc_to_overview_and_id_from_char_to_int_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUUID',
            new_name='Persona',
        ),
    ]
