# Generated by Django 2.2.4 on 2022-05-17 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0006_rename_UserUUID_to_Persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='user_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
    ]
