# Generated by Django 2.2.4 on 2022-05-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0007_change_fields_to_reflect_persona_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='tmdb_id',
        ),
    ]
