# Generated by Django 4.0.5 on 2022-07-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0008_rename_movie_id_to_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='list_builder.persona'),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='movies',
            field=models.ManyToManyField(related_name='in_%(class)ss', to='list_builder.movie'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='list_builder.persona'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tempmovielist',
            name='movies',
            field=models.ManyToManyField(related_name='in_%(class)ss', to='list_builder.movie'),
        ),
    ]
