# Generated by Django 4.1 on 2023-09-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0009_change_primarykeys_to_bigautofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
