# Generated by Django 4.1 on 2023-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0010_nickname_no_longer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovielist',
            name='list_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
