# Generated by Django 4.1 on 2023-10-29 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0012_updated_name_validations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Optional. 20 characters or fewer. Letters, numbers, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', max_length=20, validators=[django.core.validators.RegexValidator(message='List name can only contain letters, numbers, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', regex='^[\\w,.!:\\"\'$&+\\-()]+\\Z')]),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='list_name',
            field=models.CharField(blank=True, default='', help_text='100 characters or fewer. Letters, numbers, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', max_length=100, validators=[django.core.validators.RegexValidator(message='List name can only contain letters, numbers, basic punctuation: ,/./!/:/"/\'/$/&/+/-/() characters.', regex='^[\\w,.!:\\"\'$&+\\-()]+\\Z')]),
        ),
    ]
