# Generated by Django 4.1 on 2023-11-06 00:21

from django.db import migrations, models
import list_builder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0014_add_spaces_to_allowed_chars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Optional. 20 characters or fewer. Letters, numbers, basic punctuation: , . ! ? : \' " $ & + - ( ) characters.', max_length=20, validators=[list_builder.validators.UserInputValidator()]),
        ),
        migrations.AlterField(
            model_name='savedmovielist',
            name='list_name',
            field=models.CharField(blank=True, default='', help_text='100 characters or fewer. Letters, numbers, basic punctuation: , . ! ? : \' " $ & + - ( ) characters.', max_length=100, validators=[list_builder.validators.UserInputValidator()]),
        ),
    ]
