# Generated by Django 4.2.7 on 2023-11-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_builder', '0015_custom_validator_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='is_registered',
        ),
    ]
