name: Deploy to ECR

on:
  push:
    branches: [ deploy_to_ecr ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: moviematch              # set this to your Amazon ECR repository name

permissions:
  contents: read
  id-token: write
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code from deploy_to_ecr branch
      uses: actions/checkout@v4
      with:
        ref: deploy_to_ecr
    
    - name: Get commit timestamp
      run: |
        echo "COMMIT_TIME=$(git show -s --format=%cd --date="format:%Y-%m-%d.%H-%M-%S")" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Use the version of Node.js that your project requires

    - name: Install dependencies and run webpack
      run: |
        npm ci
        npm run bundle-deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MovieMatchDeployment
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: true
        retry-max-attempts: 4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}-${{ env.COMMIT_TIME}}
      run: |
        docker build -f ./Docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
    - name: Copy docker-compose files to S3
      run: |
        aws s3 cp ./Docker/docker-compose.deploy.yml s3://deploy-instructions/$ECR_REPOSITORY/docker-compose.yml

    - name: Run SSM Command document to update EC2
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}-${{ env.COMMIT_TIME}}
      run: |
        aws ssm send-command \
          --document-name "Update_Project" \
          --document-version "\$LATEST" \
          --targets '[{"Key":"InstanceIds","Values":["${{ secrets.AWS_PROJECTWEBSERVER_EC2_INSTANCE_ID }}"]}]' \
          --parameters '{ "ecrRegistry":["${{ env.ECR_REGISTRY }}"], "repoName":["${{ env.ECR_REPOSITORY }}"], "imageTag":["${{ env.IMAGE_TAG }}"]}' \
          --timeout-seconds 600 \
          --max-concurrency "50" \
          --max-errors "0" \
          --region ${{ env.AWS_REGION }}

  notify:
    name: Deploy Notification
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: build
    env:
      JOB_STATUS: ${{ needs.build.result }}
      JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
    - name: Set current date as env variable
      run: |
        echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        echo "NOW_UNIX=$(date +%s)" >> $GITHUB_ENV

    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Deployment ${{ env.JOB_STATUS }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.JOB_STATUS == 'success' && ':white_check_mark: *Deployment Successful* :white_check_mark:' || ':x: *Deployment Failed* :x:' }}\n\n*Time:* <!date^${{ env.NOW_UNIX }}^{date_num} {time_secs}|${{ env.NOW }}>"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n${{ github.ref_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*User:*\n${{ github.triggering_actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n${{ github.workflow }}"
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "View Github Actions workflow logs on GitHub."
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": ":computer: Go to Workflow Logs",
                    "emoji": true
                  },
                  "url": "${{ env.JOB_URL }}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "<!date^${{ env.NOW_UNIX }}^{date_long_pretty} {time_secs}|${{ env.NOW }}>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
