name: S3 Test

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: moviematch
  IMAGE_TAG: 7fedd2a9b471580a205454a632e4b5190e15e75c-2022-09-06.02-12-44
  ECR_REGISTRY: 696811202438.dkr.ecr.us-west-2.amazonaws.com
  
permissions:
  contents: read
  id-token: write

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Slack Test
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "${{ env.GITHUB_REPOSITORY }} build and push to AWS SUCCESFUL",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.GITHUB_REPOSITORY }} build and push to AWS SUCCESFUL"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
