name: S3 Test

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2 

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: AWSThere
      run: aws --version
    
    - name: Echo directory
      run: echo $(ls)
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MovieMatchS3
        aws-region: ${{ env.AWS_REGION }}
      
    - name: AWSCopy
      run: aws s3 cp ./Docker/docker-compose.yml s3://deploy-instructions/compose-files/docker-compose.yml
    
    #- name: AWSSync
    #  run: aws aws s3 cp ./Docker/docker-compose.prod.yml s3://my_bucket/compose-files/docker-compose.prod.yml
