name: S3 Test

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: moviematch
  IMAGE_TAG: b189171b36d4b6315dcd3a3e26fdf59eb77f438d-2022-09-06.19-17-52
  ECR_REGISTRY: 696811202438.dkr.ecr.us-west-2.amazonaws.com
  
permissions:
  contents: read
  id-token: write

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: MovieMatchDeployment
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Run SSM Command document to update EC2
      run: |
        aws ssm send-command \
          --document-name "Update_Project" \
          --document-version "\$LATEST" \
          --targets '[{"Key":"InstanceIds","Values":["${{ secrets.AWS_MOVIEMATCH_EC2_INSTANCE_ID }}"]}]' \
          --parameters '{ "ecrRegistry":["$ECR_REGISTRY"], "repoName":["$ECR_REPOSITORY"], "imageTag":["$IMAGE_TAG"]}' \
          --timeout-seconds 600 \
          --max-concurrency "50" \
          --max-errors "0" \
          --region ${{ env.AWS_REGION }}

    - name: Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "${{ env.ECR_REPOSITORY }} build and push to AWS SUCCESSFUL",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.ECR_REPOSITORY }} build and push to AWS SUCCESSFUL"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
